# Buildpacks to include in builder
[[buildpacks]]
id = "buildpacks/empty"
version = "0.0.1"
uri = "../../buildpacks/empty"

[[buildpacks]]
id = "buildpacks/python"
version = "0.0.1"
uri = "../../buildpacks/python"

[[buildpacks]]
uri = "docker://gcr.io/paketo-buildpacks/go:0.7.0"
version = "0.7.0"


# Order used for detection
[[order]]
  [[order.group]]
  id = "buildpacks/empty"
  version = "0.0.1"

  [[order.group]]
  id = "buildpacks/python"
  version = "0.0.1"

[[order]]
  [[order.group]]
  id = "paketo-buildpacks/go"
  version = "0.7.0"
  
# Stack that will be used by the builder
[stack]
id = "io.github.stake.samples.debian"
run-image = "distroless-python:run"
build-image = "distroless-python:build"