# Buildpack API version
api = "0.2"

[buildpack]
id = "stake/empty-cnb"
version = "0.0.1"
name = "Empty Buildpack"
homepage = "https://github.com/s-take/"

[[stacks]]
id = "io.github.stake.samples.debian"